Switch pp
cornell-netlab/petr4 pull request #247
Opened 2020-11-10 02:06 UTC by natalieisak

pretty printer using pp library

2020-11-30 16:41 UTC, hackedy requested changes
Thanks for doing this and sorry for taking so long reviewing the PR! I took a look at the diff--there's a few little things to fix before merging. I also played around with the pretty printer and tried to make a list in the rest of this comment of issues I found. It would be good to fix these before merging but I think some of them (e.g., parenthesizing arithmetic with as few parentheses as necessary) are probably more effort than they're worth.

For example here's an excerpt from `dune exec -- petr4 typecheck -I examples examples/checker_tests/good/psa-portid-using-newtype2.p4`. I wouldn't expect this to put a newline after the `&`.
```
        standard_metadata.egress_spec = (PortId_t)(((PortIdUInt_t)(standard_metadata.egress_spec)
                                                       &
                                                       (PortIdUInt_t)(mask)));
```

Another thing is that lists (of parameters or arguments) look like `a,b,c` instead of `a, b, c`.

There's funny whitespace around table keys. I would write this like `meta.data[0].da: exact;`
```
        key = {
            meta.data[0].da : exact ;
        }
```

Finally there's things we already talked about with wrapping and parenthesization. In core.p4 right now the pretty printer does this.
```
    void extract<
    T0>(out T0 variableSizeHeader,in bit<32> variableFieldSizeInBits);
```
I'd prefer something like this, which is actually less wide than what the pretty printer is doing right now.
```
    void extract<T0>(out T0 variableSizeHeader,
                     in bit<32> variableFieldSizeInBits);
```

And here's an example of over-parenthesization of arithmetic expressions. `petr4 typecheck -I examples examples/checker_tests/good/scalarmeta-bmv2.p4` includes
```
        meta.counter = (meta.counter - 1);
```

2020-11-30 16:41 UTC, hackedy commented on test/test.ml
> +     Format.printf "%s" ((Parse.parse_string (get_name ["../examples"] (example_path ["checker_tests"; "good"; "coree.p4"]))) |> Prettypp.format_program |> to_string);   *)
Can you delete this commented out code and get rid of coree.p4? It's a duplicate of pragma-string.p4 in the same directory anyway.

2020-11-30 16:41 UTC, hackedy commented on lib/test_pp
> +open prettypp
Is this a stray file?

2020-11-30 16:41 UTC, hackedy commented on lib/pp.ml
> +module List = struct
We should use `pp` from OPAM--try adding it to the dependencies in `petr4.opam` (the "depends" clause) and `lib/dune` (the `(libraries ...)` list) and deleting this file.

2020-11-30 16:41 UTC, hackedy commented on lib/pretty.ml
>   * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
Let's delete this old pretty printer and replace any uses of it with the new one.

2020-11-30 16:41 UTC, hackedy commented on lib/types.ml
>  type name =
This all looks like whitespace changes, please revert

2020-11-30 16:41 UTC, hackedy commented on test/test.ml
>          test_case name `Quick (excl_test name)) excluded_good_files);
Let's uncomment the other tests. You can run just the pp tests by running `dune exec -- ./test.exe test pp` from inside the `test/` folder. The last argument there, `pp`, can be any regular expression you want that matches "round trip pp tests good" (or whatever tests you want to run).

2020-12-08 04:23 UTC, natalieisak commented
Hi @jnfoster! This version includes the most recent edits, if you'd like to take a look. I think the printer is getting there, except for mainly 3 issues. I'll keep playing around with it this week, but if you see any fixes that'd be great!  
1)  Random splits in types. Ex: 
extern void hash<O,T8,D,
M>(out O result,in HashAlgorithm algo,in T8 base,in D data,in M max);

2) Opening brackets going to new lines. Ex: 
apply
    {
    packet_io_ingress.apply(hdr, fabric_metadata, standard_metadata);
    filtering.apply(hdr, fabric_metadata, standard_metadata);
    forwarding.apply(hdr, fabric_metadata, standard_metadata);
  }

3) Breaks happening earlier than expected with parameters. Ex:
control
  PacketIoIngress(inout parsed_headers_t hdr,
                  inout fabric_metadata_t fabric_metadata,
                  inout standard_metadata_t standard_metadata)
  {

Also, @hackedy you suggested earlier today using a vbox for parameter declarations. I did some thinking and pp has an hvbox, which prints everything horizontally, unless it can't fit (then it'll print everything vertically). I think using the vbox vs hvbox is a stylistic choice - do you have a preference?

2020-12-08 05:01 UTC, hackedy commented
Using an hvbox sounds right to me. I think I missed that in pp.mli.

2020-12-16 13:55 UTC, hackedy commented
I'll take one more look at this today and see if I can fix some of the weird breaks in function/action/control declarations that Natalie mentioned in the meeting earlier.

2021-01-12 16:04 UTC, hackedy approved these changes

2021-01-12 18:44 UTC, merged